# Generated by Django 2.1.7 on 2019-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatasi', '0002_auto_20190401_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='player_pics'),
        ),
    ]
