# Generated by Django 2.1.7 on 2019-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatasi', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('netball', 'Netball')], max_length=10),
        ),
    ]
