# Generated by Django 2.1.7 on 2019-03-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='Aquinas', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='sport',
            field=models.CharField(default='football', max_length=100),
        ),
    ]
