# Generated by Django 2.1.7 on 2019-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190327_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sport',
            field=models.CharField(default='', max_length=100),
        ),
    ]
